steps:
  # For CI/CD on Google Cloud Build & GKE
  # 1 - Build images
  - name: "gcr.io/cloud-builders/docker"
    args: ["compose", "-f", "docker-compose.yml", "build"]

  # 2- Push images to private repository
  - name: "gcr.io/cloud-builders/docker"
    args: ["compose", "push"]

  # 3 - Deploy images to cluster
  # gke-deploy is a wrapper for 'kubectl apply'
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=k8s-manifests/deployments/
      - --location=asia-southeast1
      - --cluster=recipee-cluster-1
      - -R

substitutions:
  _APP_VERSION: 0.0.5

# Global vars for CI pipeline
options:
  env:
    - "PROJECT_ID=$PROJECT_ID"
    - "APP_VERSION=${_APP_VERSION}"
  secretEnv:
    [
      "MYSQL_URL_BACKEND",
      "MYSQL_URL_AUTH",
      "REDISHOST",
      "REDISPORT",
      "SCRAPPER_URL",
      "KEY_URL",
      "SCRAPPER_SERVER_KEY",
    ]

# Secrets
# Used to supply environment variables to CI/CD pipeline
availableSecrets:
  secretManager:
    - versionName: projects/621005217238/secrets/MYSQL_URL_BACKEND/versions/2
      env: "MYSQL_URL_BACKEND"
    - versionName: projects/621005217238/secrets/MYSQL_URL_AUTH/versions/2
      env: "MYSQL_URL_AUTH"
    - versionName: projects/621005217238/secrets/REDISHOST/versions/3
      env: "REDISHOST"
    - versionName: projects/621005217238/secrets/REDISPORT/versions/1
      env: "REDISPORT"
    - versionName: projects/621005217238/secrets/SCRAPPER_URL/versions/3
      env: "SCRAPPER_URL"
    - versionName: projects/621005217238/secrets/KEY_URL/versions/3
      env: "KEY_URL"
    - versionName: projects/621005217238/secrets/SCRAPPER_SERVER_KEY/versions/2
      env: "SCRAPPER_SERVER_KEY"
