version: "3.9"

#####
# - Networks and Secrets are used with Docker Compose in local environment only
# - sensitive data are mounted with secrets for local setup, or managed by secret environment variables in production
# 'Image' key here is used for pushing to Artifact Registry in the cloud after the build steps. Comment it out when composing locally
#####
services:
  frontend:
    build:
      context: ./client/recipe-shopper
      dockerfile: Dockerfile
    container_name: frontend
    image: "asia-southeast1-docker.pkg.dev/$PROJECT_ID/recipee-shopping/project-frontend"
    networks:
      - core
    ports:
      - "80:80"
    links:
      - auth
      - backend
    depends_on:
      - auth
      - backend

  backend:
    build:
      context: ./server/backend-server/recipe-shopper
      dockerfile: Dockerfile
    container_name: backend
    image: "asia-southeast1-docker.pkg.dev/$PROJECT_ID/recipee-shopping/project-backend"
    secrets:
      - MYSQL_URL_BACKEND
      - SCRAPPER_URL
      - KEY_URL
      - GOOGLE_CREDENTIALS
    environment:
      MYSQL_URL_BACKEND: "$MYSQL_URL_BACKEND"
      SCRAPPER_URL: "$SCRAPPER_URL"
      KEY_URL: "$KEY_URL"
      GOOGLE_CREDENTIALS: "$GOOGLE_CREDENTIALS"
    networks:
      - core
    ports:
      - "8000:8080"
    links:
      - auth
      # - scrapper
    depends_on:
      - auth
      # - scrapper

  auth:
    build:
      context: ./server/auth-server/jwt-auth-server
      dockerfile: Dockerfile
    container_name: auth
    image: "asia-southeast1-docker.pkg.dev/$PROJECT_ID/recipee-shopping/project-auth"
    secrets:
      - REDISPORT
      - REDISHOST
      - REDISUSER
      - REDISPASSWORD
      - MYSQL_URL_AUTH
    networks:
      - core
    ports:
      - "8010:8080"
    depends_on:
      - redis

  # scrapper:
  #   build:
  #     context: ./server/python-server/web_scrapper_server
  #     dockerfile: Dockerfile
  #   container_name: scrapper
  #   image: "asia-southeast1-docker.pkg.dev/$PROJECT_ID/recipee-shopping/project-scrapper"
  #   secrets:
  #     - scrapper_server_key
  #   networks:
  #     - core
  #   ports:
  #     - "8020:8000"

  redis:
    build: ./redis
    container_name: redis
    # Deployment machine may not run this command automatically. Remember to set it
    command: "redis-server --save 60 10 --requirepass $REDISPASSWORD"
    image: "asia-southeast1-docker.pkg.dev/$PROJECT_ID/recipee-shopping/project-redis"
    networks:
      - core
    ports:
      - "6379:6379"

secrets:
  MYSQL_URL_BACKEND:
    environment: "MYSQL_URL_BACKEND"
  MYSQL_URL_AUTH:
    environment: "MYSQL_URL_AUTH"
  REDISHOST:
    environment: "REDISHOST"
  REDISPORT:
    environment: "REDISPORT"
  REDISUSER:
    environment: "REDISUSER"
  REDISPASSWORD:
    environment: "REDISPASSWORD"
  SCRAPPER_URL:
    environment: "SCRAPPER_URL"
  KEY_URL:
    environment: "KEY_URL"
  GOOGLE_CREDENTIALS:
    environment: "GOOGLE_CREDENTIALS"
  scrapper_server_key:
    environment: "SCRAPPER_SERVER_KEY"
  GOOGLE_APPLICATION_CREDENTIALS:
    file: ./server/backend-server/recipe-shopper/src/main/resources/recipeee-gmail.json

networks:
  core:
    driver: bridge
