version: "3.9"

services:
  frontend:
    build:
      context: ./client/recipe-shopper
      dockerfile: Dockerfile
    container_name: frontend
    image: "asia-southeast1-docker.pkg.dev/recipe-shopper-5d242/recipee-shopping/project-frontend"
    networks:
      - core
    ports:
      - "80:80"
    links:
      - auth
      - backend
    depends_on:
      - auth
      - backend

  backend:
    build:
      context: ./server/backend-server/recipe-shopper
      dockerfile: Dockerfile
    container_name: backend
    image: "asia-southeast1-docker.pkg.dev/recipe-shopper-5d242/recipee-shopping/project-backend"
    # Secrets are used with Docker Compose
    secrets: 
      - MYSQL_URL_BACKEND
      - SCRAPPER_URL
      - KEY_URL
      - GOOGLE_CREDENTIALS
    # Env vars are used for Cloud build/ deployment
    # environment:
    #   MYSQL_URL_BACKEND: "${MYSQL_URL_BACKEND}"
    #   SCRAPPER_URL: "${SCRAPPER_URL}"
    #   KEY_URL: "${KEY_URL}"
    #   GOOGLE_CREDENTIALS: "${GOOGLE_CREDENTIALS}"
    networks:
      - core
    # TODO remove before production
    ports:
      - "8000:8080"
    links:
      - scrapper
      - auth
    depends_on:
      - auth
      - scrapper

  auth:
    build:
      context: ./server/auth-server/jwt-auth-server
      dockerfile: Dockerfile
    container_name: auth
    image: "asia-southeast1-docker.pkg.dev/recipe-shopper-5d242/recipee-shopping/project-auth"
    secrets:
      - REDISPORT
      - REDISHOST
      - REDISUSER
      - REDISPASSWORD
      - MYSQL_URL_AUTH
      - GOOGLE_APPLICATION_CREDENTIALS
    # environment:
    #   REDISPORT: "${REDISPORT}"
    #   REDISHOST: "${REDISHOST}"
    #   REDISUSER: "${REDISUSER}"
    #   REDISPASSWORD: "${REDISPASSWORD}"
    #   MYSQL_URL_AUTH: "${MYSQL_URL_AUTH}"
    networks:
      - core
    ports:
      - "8010:8080"

  scrapper:
    build:
      context: ./server/python-server/web_scrapper_server
      dockerfile: Dockerfile
    container_name: scrapper
    image: "asia-southeast1-docker.pkg.dev/recipe-shopper-5d242/recipee-shopping/project-scrapper"
    secrets:
      - scrapper_server_key
    # environment:
    #   scrapper_server_key: "${scrapper_server_key}"
    networks:
      - core
    ports:
      - "8020:8000"

secrets:
  MYSQL_URL_BACKEND:
    environment: "MYSQL_URL_BACKEND"
  MYSQL_URL_AUTH:
    environment: "MYSQL_URL_AUTH"
  REDISHOST:
    environment: "REDISHOST"
  REDISPORT:
    environment: "REDISPORT"
  REDISUSER:
    environment: "REDISUSER"
  REDISPASSWORD:
    environment: "REDISPASSWORD"
  SCRAPPER_URL:
    environment: "SCRAPPER_URL"
  KEY_URL:
    environment: "KEY_URL"
  GOOGLE_CREDENTIALS:
    environment: "GOOGLE_CREDENTIALS"
  scrapper_server_key:
    environment: "SCRAPPER_SERVER_KEY"
  GOOGLE_APPLICATION_CREDENTIALS:
    environment: "GOOGLE_APPLICATION_CREDENTIALS"

networks:
  core:
    driver: bridge
