---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "server-scrapper-1"
  namespace: "backend"
  labels:
    app: "server-scrapper-1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "server-scrapper-1"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "server-scrapper-1"
    spec:
      containers:
        - name: "project-scrapper-1"
          image: "asia-southeast1-docker.pkg.dev/recipe-shopper-5d242/recipee-shopping/project-scrapper:0.0.4"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              port: 8000
              path: /scrape/health
          resources:
            limits:
              cpu: "1"
              ephemeral-storage: 300Mi
              memory: 1.2Gi
            requests:
              cpu: 400m
              ephemeral-storage: 300Mi
              memory: 600Mi
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "server-scrapper-autoscaler"
  namespace: "backend"
  labels:
    app: "server-scrapper-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "server-scrapper-1"
    apiVersion: "apps/v1"
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: "Resource"
      resource:
        name: "memory"
        target:
          type: "Utilization"
          averageUtilization: 80
