---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "server-frontend-1"
  namespace: "backend"
  labels:
    app: "server-frontend-1"
# Deployment Spec - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/#DeploymentSpec
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "server-frontend-1"
  strategy:
    type: RollingUpdate
  # Pod Template - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-template-v1/#PodTemplateSpec
  template:
    metadata:
      labels:
        app: "server-frontend-1"
    # Pod Spec - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodSpec
    spec:
      containers:
        - name: "project-frontend-1"
          image: "asia-southeast1-docker.pkg.dev/recipe-shopper-5d242/recipee-shopping/project-frontend:0.1.1"
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 400Mi
              memory: 500Mi
            requests:
              cpu: 200m
              ephemeral-storage: 100Mi
              memory: 200Mi
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "server-frontend-autoscaler"
  namespace: "backend"
  labels:
    app: "server-frontend-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "server-frontend-1"
    apiVersion: "apps/v1"
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80
