---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "server-api-1"
  namespace: "backend"
  labels:
    app: "server-api-1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "server-api-1"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "server-api-1"
    spec:
      volumes:
        - name: service-key
          secret:
            secretName: google-services-credential
      containers:
        - name: "project-backend-1"
          image: "asia-southeast1-docker.pkg.dev/recipe-shopper-5d242/recipee-shopping/project-backend:0.0.5"
          volumeMounts:
            - mountPath: /var/secrets/google
              name: service-key
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/key.json"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/health
          resources:
            limits:
              cpu: 800m
              ephemeral-storage: 800Mi
              memory: 1.2Gi
            requests:
              cpu: 400m
              ephemeral-storage: 400Mi
              memory: 600Mi
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "server-api-autoscaler"
  namespace: "backend"
  labels:
    app: "server-api-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "server-api-1"
    apiVersion: "apps/v1"
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80
