# development server
server:
  port: 8090

# Logging
logging:
  level:
    org:
      springframework:
        security: debug
        jdbc:
          core:
            JdbcTemplate: debug
            StatementCreatorUtils: trace
    web: debug
    com:
      recipeshopper:
        jwtauthserver: debug

# Overrides
spring:
  redis:
    user:
    password:
  devtools:
    add-properties: true
