---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "ingress-controller-1"
  namespace: "backend"
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: recipee-ingress-ip
spec:
  rules:
    - http:
        paths:
          - path: "/*"
            backend:
              service:
                name: "server-frontend-1-service"
                port:
                  number: 80
            pathType: "ImplementationSpecific"
    - http:
        paths:
          - path: "/api/*"
            backend:
              service:
                name: "server-api-1-service"
                port:
                  number: 80
            pathType: "ImplementationSpecific"
