---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "ingress-controller"
  namespace: "backend"
spec:
  defaultBackend:
    service:
      name: "server-frontend-service"
      port:
        number: 80
  rules:
  - http:
      paths:
      - path: "/api/*"
        backend:
          service:
            name: "server-frontend-service"
            port:
              number: 80
        pathType: "ImplementationSpecific"
    host: "*.recipee-shopping.com"
status:
  loadBalancer: {}
